# useful aliases
# don't group names for long listing
alias ls='ls -G'
# add color scheme support for tmux in iterm2
alias tmux="TERM=screen-256color-bce tmux"
# start a simple python3 http server
alias simpleHttp="python3 -m http.server --cgi 8000"

# add git completion
source ~/.git-completion.bash
# add git prompt
source ~/.git-prompt.sh
# change prompt to show git branch
PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

# Export GPG_TTY for gpg
export GPG_TTY=$(tty)
# Add /usr/local/sbin to $PATH
export PATH="/usr/local/sbin:$PATH"
